// Static onboarding reference emitted by `vsync docs`.
//
// Lives as a string export so it ships with the binary and stays in
// sync with the verb set. Pipe to a file if you want to commit it:
//   vsync docs > infra/AGENTS.md

export const DOCS_MD = `# vsync — onboarding reference

Generated by \`vsync docs\` and intended to be committed at the path of
your choice (\`infra/AGENTS.md\`, \`infra/CLAUDE.md\`, etc.) so AI agents
and teammates landing in this repo know where secrets live and how to
work with them.

## What this repo uses

Secrets sync via \`@muthuishere/vsync\`. The canonical store is an
S3-compatible bucket; per-machine state lives at
\`~/.config/vsync/\` plus an OS keychain entry under service
\`tools.vsync\`.

## Where secret content lives

\`\`\`
infra/vault/
  dev/
    .env.dev
    some-secret.json
    ...
  production/
    .env.production
\`\`\`

(\`infra/vault/<env>\` is the default — a per-(repo, env) override may
point elsewhere; check \`~/.config/vsync/<repo>/env_<env>\` for
\`files.vaultFolder\`.)

Apps point dotenv (or equivalent) at the in-vault path:

\`\`\`js
dotenv.config({ path: \`infra/vault/\${env}/.env.\${env}\` });
\`\`\`

## Commands

| Command | Purpose |
|---|---|
| \`vsync init <env>\` | First-time setup: generate AES key, write per-repo config, create vault folder. Re-runnable. |
| \`vsync export <env>\` | Write a passphrase-encrypted \`.share\` file to send a teammate (file + passphrase on different channels). |
| \`vsync import <env> <file>\` | Install a teammate's \`.share\` file. No prior init required. |
| \`vsync push <env>\` | Encrypt the vault folder and upload to S3. |
| \`vsync pull <env>\` | Download the latest from S3 and unzip into the vault folder (auto-backs up the existing folder first). |
| \`vsync versions <env>\` | List the available versions on S3 (read-only, no decrypt). |
| \`vsync sync <env> <gh\\|gcp\\|aws\\|azure\\|vault>\` | Push the vault's \`.env.<env>\` KVs out to GitHub Repo Secrets, GCP Secret Manager, AWS Secrets Manager, Azure Key Vault, or HashiCorp Vault KV v2. One target per invocation. |
| \`vsync docs\` | Print this reference. |

Every command takes \`--repo=<name>\` to override the auto-detected repo
name and \`--interactive\` to force prompts. Each command works fully
via flags or fully via prompts.

## Recovering a local backup

Each \`vsync pull\` writes the prior vault folder to
\`~/.config/vsync/backups/<env>-<ts>.zip.enc\` (two-deep rolling buffer).
The format is AES-256-GCM with the same per-(repo, env) keychain key
plus the salt from the per-repo config. To decrypt by hand:

1. Get the keychain key:
   - macOS: \`security find-generic-password -s tools.vsync -a <repo>/<env> -w\`
   - Linux: \`secret-tool lookup service tools.vsync account <repo>/<env>\`
2. Get the salt: \`gunzip -c ~/.config/vsync/<repo>/env_<env> | jq -r .encryption.salt\`
3. The envelope is \`RQE1\` (4-byte magic) + 12-byte IV + AES-GCM ciphertext.
   Derive \`AES-256-GCM key = PBKDF2-SHA256(keychain-key, salt, 600k)\`.

Easier: just \`vsync pull\` again to restore from S3.

## Audit log

Every \`pull\`, \`push\`, \`import\`, and \`export\` appends a CSV row to
\`s3://<bucket>/<repo>/<env>/audit.csv\` capturing timestamp, action,
hostname, local IP, OS user, git email, and a free-form \`meta\` JSON
cell. Best-effort: an audit-write failure prints a warning and never
fails the parent command.

On by default. Three ways to opt out:

- \`--no-audit\` on a single invocation
- \`cfg.audit.enabled: false\` in the per-repo config
- \`vsync init <env> --audit=off\` at setup (or pick "off" at the first-time prompt)

Tag a row with context via four merging input paths, in increasing
priority order: \`$VSYNC_AUDIT_META\` (JSON) < \`$VSYNC_AUDIT_NOTE\` <
\`--meta key=value\` (repeatable) < \`--note=<text>\`. Later sources
overwrite same-named keys from earlier ones.

View the log with \`vsync audit <env>\` (\`--limit=N\`, \`--all\`, \`--csv\`).
Pretty table by default, newest first; \`--csv\` is raw passthrough.

Honesty clause: transparency for honest users, not tamper-proof
(anyone with bucket write can rewrite the file). It can't recover
already-pulled secrets either — once a teammate has pulled, they hold
a local copy.

## Rules for AI agents working in this repo

1. **Never commit anything under \`infra/vault/\`.** Add it to
   \`.gitignore\` if missing.
2. **Never read or edit files under \`~/.config/vsync/\` directly.**
   Use the CLI verbs.
3. **Never paste keychain keys or salts into source code, comments,
   PR descriptions, or chat.** They're machine-local secrets.
4. **Routing config (sync.gh.repo, sync.gcp.project) is per-(repo, env).**
   Read it from \`~/.config/vsync/<repo>/env_<env>\` if you need to know
   the GH repo or GCP project the team syncs to. Don't hardcode it.
5. **If a command asks for a passphrase or share-file path, surface the
   prompt to the human user.** Don't auto-fill or skip.
`;
