name: python-vsync-s3-client tests

on:
  push:
    paths:
      - "libraries/python/**"
      - "docs/specs/test-vectors/**"
      - ".github/workflows/python-test.yml"
  pull_request:
    paths:
      - "libraries/python/**"
      - "docs/specs/test-vectors/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    defaults:
      run:
        working-directory: libraries/python
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: pip install -e ".[dev]"
      - run: pytest -v
